### ISSUE TITLE
feat(core): keyboard accessibility support (on by default)

### ISSUE THREAD

**Issue by lmenus** [prescottprue/react-google-button#18]
Hello, I think it would be great if this button was accessible using the keyboard. This can be achieved by adding `tabindex="0"` and `role="button"` to the wrapper `<div>` tag that has click listener attached to it.

**Comment by prescottprue** [comment]
Love the idea, thanks for reporting! It would be cool to enable/disable that as well.

Open to a PR if you get a chance, otherwise, I will try to get to it this week.

**Comment by lmenus** [comment]
@prescottprue Yes definitely, users shouldn’t be able to focus this button if it’s disabled imo. Btw why doesn’t it use <button> as a wrapper?

**Comment by prescottprue** [comment]
Not sure what you mean by "why doesn't it use as a wrapper" - guessing you mean something why not support using it as a Higher Order Component wrapper? If so, the answer is just that I haven't needed it yet, but totally open to the idea.

We could instead do a component prop similar to [how material-ui does their button](https://material-ui.com/api/button/), it may be more clear than an HOC.

**Comment by lmenus** [comment]
Hi @prescottprue, did you have time to look into this? Thanks!

**Comment by prescottprue** [comment]
@lmenus totally forgot about this, thanks for the reminder. [`v0.6.0-alpha`](https://github.com/prescottprue/react-google-button/releases/tag/v0.6.0-alpha) was released to the `next` tag (and branch).

Was going to look into a few more changes before releasing `v0.6.0` to `latest`, but it should be pretty soon.

**Comment by lmenus** [comment]
Hi @prescottprue, sorry for the late reply. Tested it now and works great, thank you!
