### ISSUE TITLE
jsnext:main

### ISSUE THREAD

**Issue by aaronburmeister** [prescottprue/react-google-button#4]
Hello there, thanks for this awesome package.

Webpack get's confused when loading `react-google-button` because it tries to parse the `jsnext:main` entrypoint but does not know how to handle `export default from ...`, class variables and JSX.

Shouldn't `jsnext:main` only contain ES2015 code?

**Comment by prescottprue** [comment]
Yes, that is correct. Surprised this wasn't caught until now, but thanks for pointing it out
